check for existing final output files and exit if present, create qc dir for fastplong and multiqc.

diff --git a/nageno b/nageno
--- a/nageno
+++ b/nageno
@@ -151,6 +151,7 @@ if [[ "$SUBCOMMAND" == "analysis" && ( -z "$DIR" || -z "$ANNO" || -z "$REF" || -
     exit 1
 fi
 
+
 # Assign default values if not provided
 MANAGER=${MANAGER:-$DEFAULT_MANAGER}
 THREADS=${THREADS:-$DEFAULT_THREADS}
@@ -189,6 +190,18 @@ MOD="_q${QUANT}_Q${MIN_Q}"
 MOD_STRP="q${QUANT}_Q${MIN_Q}"
 MAPQ_MOD="_MAPQ${MAPQ}"
 DATE=$(date +'%Y-%m-%d')
+
+# Check if plot output files exist already
+if [[ "$SUBCOMMAND" == "plot" && -f "$ANALYSIS_DIR/ClairS-TO/SNV_genotyping_results.tsv" ]]; then
+    echo "Error: It seems like genotyping has already been performed in the --analysis-dir you specified. Use a different one to prevent overwriting data."
+    exit 1
+fi
+
+# Check if analysis output files exist already
+if [[ "$SUBCOMMAND" == "analysis" && -d "$ANALYSIS_DIR/ClairS-TO" ]]; then
+    echo "Error: It seems like variant-calling has already been performed in the --analysis-dir you specified. Use a different one to prevent overwriting data."
+    exit 1
+fi
 
 # log files
 LOG_DIR="$ANALYSIS_DIR/logs"
