re-activate stop option if output exists already

diff --git a/nageno b/nageno
--- a/nageno
+++ b/nageno
@@ -198,10 +198,10 @@ if [[ "$SUBCOMMAND" == "plot" && -f "$ANALYSIS_DIR/ClairS-TO/SNV_genotyping_resu
 fi
 
 # Check if analysis output files exist already
-#if [[ "$SUBCOMMAND" == "analysis" && -d "$ANALYSIS_DIR/ClairS-TO" ]]; then
-#    echo "Error: It seems like variant-calling has already been performed in the --analysis-dir you specified. Use a different one to prevent overwriting data."
-#    exit 1
-#fi
+if [[ "$SUBCOMMAND" == "analysis" && -d "$ANALYSIS_DIR/ClairS-TO" ]]; then
+    echo "Error: It seems like variant-calling has already been performed in the --analysis-dir you specified. Use a different one to prevent overwriting data."
+    exit 1
+fi
 
 # log files
 LOG_DIR="$ANALYSIS_DIR/logs"
